### ISSUE TITLE
Please specify a license

### ISSUE THREAD

**Issue by wrandelshofer** [fastfloat/supplemental_test_files#1]
I would like to use the test files in project https://github.com/wrandelshofer/FastDoubleParser
However, without a license, I don't know whether this is permitted.

Can you please specify a license for the files in this project?

**Comment by lemire** [comment]
As indicated in the README, the files were prepared by Nigel. If you need to have a license, I recommend reaching out to him.

**Comment by wrandelshofer** [comment]
Ok, I am going to ask him. Thank you!

**Comment by lemire** [comment]
@wrandelshofer Note that I am not trying to be unhelpful. I just don't want to grant a license that would not be valid.

**Comment by lemire** [comment]
I would love to setup a license here.

**Comment by wrandelshofer** [comment]
You are always very helpful! 🤗

🤫 But who (the hell) is Nigel? 

... I thought he would be one of the committers of this project, or of the fastfloat project. But I could not find him. 😂

**Comment by lemire** [comment]
Nigel: https://github.com/nigeltao

ping @nigeltao

**Comment by nigeltao** [comment]
@lemire it might help if the supplemental_test_files README.md linked back to
https://github.com/nigeltao/parse-number-fxx-test-data
since it already has a LICENSE file (Apache 2).
https://github.com/nigeltao/parse-number-fxx-test-data/blob/main/LICENSE

**Comment by lemire** [comment]
@wrandelshofer @nigeltao Thanks guys!

**Comment by wrandelshofer** [comment]
Thank you, Nigel! 🤗

**Comment by lemire** [comment]
@nigeltao I am adding a link.
