### ISSUE TITLE
Please provide tagged release of supplemental_test_files

### ISSUE THREAD

**Issue by StefanBruens** [fastfloat/supplemental_test_files#2]
The fast_float build just fetches the latest HEAD. This is problematic for several reasons:

1. You may add a test file which fails with an earlier fast_float version.
2. It is quite cumbersome to fetch a specific release as a tarball - while `https://github.com/fastfloat/supplemental_test_files/archive/7cc512a7c60361ebe1baf54991d7905efdc62aa0.tar.gz` works as a URL, it is non-descriptive and also not binary stable (see https://docs.github.com/en/repositories/working-with-files/using-files/downloading-source-code-archives#stability-of-source-code-archives).

Preferably, on each fast_float release supplemental_test_files is tagged with the same version.

**Comment by lemire** [comment]
> Preferably, on each fast_float release supplemental_test_files is tagged with the same version.

These files are static. I don't expect them to change.

**Comment by lemire** [comment]
Done: https://github.com/fastfloat/supplemental_test_files/releases/tag/1.0.0
